apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /manager/home
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
#    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafAclArn }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: {{ .Values.albGroupName | default "tetra-alb" }}
    kubernetes.io/ingress.class: alb
  name: {{ .Values.chartName | default "tetra-ocpp" }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.chartName | default "tetra-ocpp" }}
            port:
              number: {{ .Values.ocppServicePort }}
        path: /
        pathType: Exact
      - backend:
          service:
            name: {{ .Values.chartName | default "tetra-ocpp" }}
            port:
              number: {{ .Values.ocppServicePort }}
        path: /manager
        pathType: Prefix
      - backend:
          service:
            name: {{ .Values.chartName | default "tetra-ocpp" }}
            port:
              number: {{ .Values.ocppServicePort }}
        path: /services
        pathType: Prefix
      - backend:
          service:
            name: {{ .Values.chartName | default "tetra-ocpp" }}
            port:
              number: {{ .Values.ocppServicePort }}
        path: /static
        pathType: Prefix
      - backend:
          service:
            name: {{ .Values.chartName | default "tetra-ocpp" }}
            port:
              number: {{ .Values.ocppServicePort }}
        path: /api/v1/chargepoint
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.chartName | default "tetra-ocpp" }}-ws"
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/healthcheck-path: /manager/home
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":8440}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.albWsGroupName | default "ocpp-ws-alb" }}
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: {{ .Values.wsHost }}
      http:
        paths:
          - path: /websocket/CentralSystemService
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.chartName | default "tetra-ocpp" }}
                port:
                  number: {{ .Values.ocppServicePort }}
