apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chartName | default "tetra-ocpp" }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.ocppServicePort }}
      targetPort: {{ .Values.ocppContainerPort }}
      nodePort: {{ .Values.ocppNodePort }}
  selector:
    app: {{ .Values.chartName | default "tetra-ocpp" }}
  type: NodePort

